apiVersion: v1
data:
  access_key: Rk9ma3NMZFFMMzJ0VGFad0FKQ2xZd1JiQW1ZRnoyYlprN016OEJORQ==
  key_id: QUtJQVZSVVZXRzQ0Q1BRT1IzVTY=
kind: Secret
type: Opaque
metadata:
  creationTimestamp: null
  name: awssecret
