apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-app-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       "Deployment"
    name:       "my-app"
  updatePolicy:
    updateMode: "off"
  resourcePolicy:
    containerPolicies:
    - containerName: "my-app-container"
      minAllowed:
        cpu: "100m"
        memory: "64Mi"
      maxAllowed:
        cpu: "200m"
        memory: "128Mi"
      controlledValues: "Requests" # VPA will adjust resource requests only