FROM node:22 AS build-env 
WORKDIR /app
COPY package*.json . 
RUN npm install
COPY . .

FROM gcr.io/distroless/nodejs22-debian12
ENV NODE_ENV=dev 
ENV PORT=3000
ENV LOKI_HOST=http://localhost:3100
COPY --from=build-env /app /app
WORKDIR /app
EXPOSE 3000
CMD ["server.js"]