deploymentMode: SingleBinary

loki:
  auth_enabled: false

  commonConfig:
    storage:
      type: filesystem

  storage_config:
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

service:
  type: NodePort
  # nodePort: 31000
  port: 3100