apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod-3
spec:
  containers:
    - name: configmap-demo-container-3
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: configmap-3 