apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod-1
spec:
  containers:
    - name: configmap-demo-container-1
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: configmap-1