apiVersion: v1
kind: Pod
metadata:
  name: checkpod
  namespace: dev-team
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "100Mi"
        cpu: "300m"