apiVersion: v1
kind: Pod
metadata:
  name: secretpassvalue-pod
spec:
  containers:
    - name: secretpassvalue-container
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: password