apiVersion: v1
kind: Pod
metadata:
  name: secretpassdatafile-pod
spec:
  containers:
    - name: secretpassdatafile-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: demo-secretdatafile